"""Render the fee-reality benchmark block from the trials ledger (#646).

**Nothing here computes a result.** Every number is read out of
`docs/experiments/trials-ledger.jsonl` -- the hash-chained record of what was actually run --
and reformatted. That is the issue's binding constraint: the block renders the ledger's numbers
or it does not ship, because a hand-typed benchmark is a marketing claim wearing a measurement's
clothes, and this project's whole argument is the difference between those two.

Run it to regenerate the README block in place:

    python scripts/render_fee_reality.py --write

`tests/test_fee_reality_block.py` fails when the file and this script's output disagree, so the
README cannot drift away from the measurement without the suite saying so.

**Parsing prose is deliberate, and its failure mode is the point.** The ledger stores the fee
curve as a recorded sentence rather than a table, because that row was written by the experiment
that produced it and rewriting history to suit a renderer would be the tail wagging the dog. So
this parses it -- strictly, with every pattern anchored, raising on anything it does not
recognise. A parse that silently produced three of four assets would be exactly the quiet
half-truth the block exists to refuse.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import textwrap
from dataclasses import dataclass
from decimal import Decimal
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_LEDGER = _ROOT / "docs/experiments/trials-ledger.jsonl"
_README = _ROOT / "README.md"

#: The ledger session that re-priced already-ledgered configurations at additional fee rates.
_SESSION = "fee-curve-and-rsi-meanrev-2026-08-12"

BEGIN = "<!-- fee-reality:begin -- generated by scripts/render_fee_reality.py; do not edit -->"
END = "<!-- fee-reality:end -->"

COST_BEGIN = (
    "<!-- cost-distortion:begin -- generated by scripts/render_fee_reality.py; do not edit -->"
)
COST_END = "<!-- cost-distortion:end -->"

#: The two ledger rows the cost-distortion block reads. Both are hash-chained, so the block
#: cannot quote a number that is not in the record of what was run.
_RESTATEMENT = "per-product-slippage-restatement-2026-09-01"
_EXIT_AB = "triple-barrier-first-measurement-2026-09-01"

#: The taker rate this account actually pays, as the fee curve's own last column. The ledger
#: writes `fee_pct` as a fraction of notional; `_as_percent` is what turns it into the number an
#: operator recognises from a fee schedule.
_TAKER_COLUMN = "0.012"


def _as_percent(fee_pct: str) -> str:
    """`"0.012"` -> `"1.2%"`. A fee schedule quotes percentages, and a README that quoted
    fractions would make the reader do the conversion that produced #247's costing error."""
    value = Decimal(fee_pct) * 100
    return f"{value.normalize():f}%"


@dataclass(frozen=True)
class AssetCurve:
    """One asset's measured profit factor across the fee sweep."""

    asset: str
    trades: int
    #: fee_pct (as written in the ledger) -> profit factor, in the ledger's own column order.
    by_fee: dict[str, str]
    #: The MEASURED break-even fee, bracketed by real cells rather than interpolated.
    break_even_pct: str


def _row(ledger_text: str) -> dict:
    """The one ledger row carrying the fee curve, or a loud failure."""
    rows = [json.loads(line) for line in ledger_text.splitlines() if line.strip()]
    curves = [
        r
        for r in rows
        if r.get("session") == _SESSION and "fee_curve" in r.get("params", {})
    ]
    if len(curves) != 1:
        raise SystemExit(
            f"expected exactly one {_SESSION!r} row carrying a fee_curve, found {len(curves)}. "
            "The ledger is append-only and hash-chained, so this means the renderer's "
            "expectation is stale -- not that the record is wrong."
        )
    return curves[0]


def parse(ledger_text: str) -> tuple[list[AssetCurve], list[str], str]:
    """`(curves, fee columns, the rule the curve was measured on)` from the ledger's own prose."""
    params = _row(ledger_text)["params"]
    curve = params["fee_curve"]

    columns = re.search(r"PF by fee_pct ([\d./]+):", curve)
    if columns is None:
        raise SystemExit("could not find the fee-column list in the ledger's fee_curve text")
    fees = columns.group(1).split("/")

    # `BTC (n=123) 1.090/0.961/...` -- anchored on the parenthesised trade count so a sentence
    # elsewhere in the row cannot match by accident.
    # `\d+\.\d+`, never `[\d.]+`: the latter is greedy enough to swallow the SENTENCE'S full
    # stop into the last asset's profit factor, which is how the first draft rendered ZEC as
    # "1.303." -- a number that is still readable, still wrong, and would have shipped.
    entries = re.findall(r"\b([A-Z]{2,10}) \(n=(\d+)\) (\d+\.\d+(?:/\d+\.\d+)+)", curve)
    if not entries:
        raise SystemExit("could not find any per-asset fee curve in the ledger's fee_curve text")

    # `=> 0.068%` closes each measured bracket; the rsi_meanrev one names its rule and is skipped.
    breakevens = dict(
        re.findall(r"(?<!rsi_meanrev )\b([A-Z]{2,10}) [\d.%>/\s-]*?=> ([\d.]+)%", curve)
    )

    curves: list[AssetCurve] = []
    for asset, trades, factors in entries:
        values = factors.split("/")
        if len(values) != len(fees):
            raise SystemExit(
                f"{asset}: {len(values)} profit factors against {len(fees)} fee columns -- "
                "refusing to render a row whose columns do not line up"
            )
        if asset not in breakevens:
            raise SystemExit(f"{asset}: no measured break-even fee in the ledger row")
        curves.append(
            AssetCurve(
                asset=asset,
                trades=int(trades),
                by_fee=dict(zip(fees, values)),
                break_even_pct=breakevens[asset],
            )
        )
    return curves, fees, params["fee_curve_rule"].split()[0]


def render(ledger_text: str) -> str:
    """The README block. Pure: same ledger in, same markdown out."""
    curves, fees, rule = parse(ledger_text)
    document = _row(ledger_text)["params"]["document"]
    zero = fees[0]

    lines = [
        BEGIN,
        "",
        "### The benchmark: the same rule, priced twice",
        "",
        f"`{rule}` on hourly bars, at each asset's best-swept configuration. The left column is",
        "the number a fee-blind backtest reports. The right is the same run priced at the taker",
        "fee this account actually pays. Nothing else changes between them.",
        "",
        f"| asset | trades | PF at {_as_percent(zero)} fee | PF at {_as_percent(_TAKER_COLUMN)} "
        "taker | break-even fee, measured |",
        "| :-- | ---: | ---: | ---: | ---: |",
    ]
    for c in curves:
        lines.append(
            f"| {c.asset} | {c.trades} | {c.by_fee[zero]} | {c.by_fee[_TAKER_COLUMN]} | "
            f"{c.break_even_pct}% |"
        )
    lines += [
        "",
        "Four of four are profitable with the fee removed. **Zero of four survive the fee that is",
        "actually charged**, and the break-even rate varies by a factor of ~26 across assets",
        "running the same rule on the same clock over the same window — the asset is a far larger",
        "lever than any parameter in an 864-trial sweep.",
        "",
        "**Read these as a comparison, never as edge estimates.** Every configuration above is the",
        "argmax of that asset's 144-cell slice, selected on the same data it is re-priced on — a",
        "maximum of 144 draws, not an expectation. The bias runs *against* the finding, which is",
        "why the comparison survives it: it inflates the arm that wins with the fee removed, and",
        "that arm still dies when the fee is charged. Break-even fees were bracketed by real",
        "cells,"
        "not interpolated. Slippage is held at 0.0005 in every cell, so the zero column is",
        "zero *fee*, not zero cost.",
        "",
        f"Source: [`{document}`]({document}), rendered from the hash-chained trials ledger by",
        "`scripts/render_fee_reality.py`.",
        "",
        END,
    ]
    return "\n".join(lines)


def _summary(ledger_text: str, trial_id: str) -> dict:
    """One trial's `summary`, or a loud failure. The ledger is append-only and hash-chained, so
    a missing row means this renderer's expectation is stale -- never that the record is wrong."""
    for line in ledger_text.splitlines():
        if not line.strip():
            continue
        row = json.loads(line)
        if row.get("trial_id") == trial_id:
            return row.get("summary") or {}
    raise SystemExit(f"no ledger row {trial_id!r} -- the renderer's expectation is stale")


def render_cost_distortion(ledger_text: str) -> str:
    """The block that states what keel's own cost model was worth getting wrong.

    Deliberately says nothing about any other framework. What was measured is keel mis-pricing
    keel, on one universe at one venue; a claim about anyone else's assumptions would be exactly
    the unsourced assertion this project refuses to make about its own results, and #646 forbids
    naming a competitor in the asset regardless.
    """
    restated = _summary(ledger_text, _RESTATEMENT)
    exit_ab = _summary(ledger_text, _EXIT_AB)

    correction = abs(Decimal(restated["pf_median_delta"]))
    improvement = Decimal(exit_ab["delta_vs_control_median_zero_fee"])
    ratio = (correction / improvement).quantize(Decimal("0.1"))

    # Paragraphs assembled as WHOLE strings, then wrapped. The first draft built them line by
    # line and every interpolated number landed mid-sentence at a line break -- fine in the
    # source, awkward in the rendered page, which is the only place it is read.
    doc = "docs/experiments/2026-09-01-per-product-slippage-restatement.md"
    paragraphs = [
        "### We mis-priced our own execution by more than any strategy change we ever made",
        (
            "Every backtest in this repository used to price fills at the **floor** of its own "
            "slippage model \u2014 the best case the model can produce, reached only at a "
            f"$500M/day anchor. Measured against the {restated['assets']} assets keel actually "
            f"holds candles for, **{restated['assets_at_the_floor']} of {restated['assets']} "
            f"reach it**: the range runs from {restated['floor_multiple_min']}\u00d7 the floor "
            f"at the most liquid to {restated['floor_multiple_max']}\u00d7 at the thinnest."
        ),
        (
            f"Re-pricing every rule per product \u2014 {restated['rules']} rules, "
            f"{restated['assets']} assets, {restated['n_trials']} trials \u2014 moved the "
            f"median profit factor across {restated['cells']} cells from "
            f"**{restated['pf_median_flat']}** to **{restated['pf_median_per_product']}**. The "
            "one cell that had cleared 1.0 no longer does."
        ),
        "| | profit factor |",
        "| :-- | --: |",
        f"| the cost-model correction | **{restated['pf_median_delta']}** |",
        f"| the best strategy improvement we have measured | **+{improvement}** |",
        (
            f"The error in how we priced execution was **{ratio}\u00d7 larger** than the "
            "largest genuine gain any change to the strategy itself produced \u2014 a better "
            "exit, measured against the same entry on the same universe. For as long as that "
            "was true, comparing strategies meant comparing them through a lens distorted by "
            "more than the differences being compared."
        ),
        (
            "**What this is and is not.** It is keel mis-pricing keel, on one venue, over one "
            "universe of cached candles \u2014 found, corrected and published. It is not a "
            "claim about any other framework's assumptions: we have not measured those, and an "
            "unsourced claim about someone else would be the exact failure this section exists "
            "to avoid making about ourselves."
        ),
        (
            "**Where the friction actually is.** Two taker legs cost "
            f"{_as_percent(str(2 * Decimal(restated['fee_pct'])))} of notional before a basis "
            "point of slippage is counted, so on the most liquid asset the fee is the "
            "overwhelming majority of the round trip and only at the thin end does slippage "
            "overtake it. A cheaper venue matters more than a better model of the book \u2014 "
            "and an honest model of the book is what tells you that."
        ),
        (
            f"Source: [`{doc}`]({doc}), rendered from the hash-chained trials ledger by "
            "`scripts/render_fee_reality.py`."
        ),
    ]
    body: list[str] = []
    for index, para in enumerate(paragraphs):
        # A table row is emitted verbatim and gets no blank line after it unless the NEXT
        # paragraph is not a row -- a blank between rows ends the table, which is how the first
        # render produced four one-row tables instead of one four-row one.
        if para.startswith("|"):
            body.append(para)
            following = paragraphs[index + 1] if index + 1 < len(paragraphs) else ""
            if not following.startswith("|"):
                body.append("")
            continue
        # A line carrying a markdown link is never wrapped: `textwrap` will happily break inside
        # the URL, and a broken link renders as literal text.
        body.extend([para] if "](" in para else textwrap.wrap(para, width=96))
        body.append("")
    lines = [COST_BEGIN, "", *body, COST_END]
    return "\n".join(lines)


def replace_block(readme: str, block: str, *, begin: str = BEGIN, end_marker: str = END) -> str:
    """`readme` with the sentinel block swapped for `block`."""
    start, end = readme.find(begin), readme.find(end_marker)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(
            f"README.md is missing the {begin!r} / {end_marker!r} sentinels -- refusing to guess "
            "the benchmark belongs"
        )
    return readme[:start] + block + readme[end + len(end_marker) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite README.md in place")
    args = parser.parse_args(argv)
    ledger = _LEDGER.read_text(encoding="utf-8")
    block = render(ledger)
    cost = render_cost_distortion(ledger)
    if not args.write:
        print(block)
        print()
        print(cost)
        return 0
    text = replace_block(_README.read_text(encoding="utf-8"), block)
    text = replace_block(text, cost, begin=COST_BEGIN, end_marker=COST_END)
    _README.write_text(text, encoding="utf-8")
    print(f"wrote the fee-reality block into {_README}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
