"""Export the `rules` table to a reviewable JSON manifest, and rebuild it from one.

**Why this exists.** A deployment's strategy library lives in the DATABASE, not in `config.yaml`.
`keel migrate` deliberately never re-seeds (see `docs/RELEASING.md`), so an in-place upgrade keeps
the rule set -- but a FRESH deployment gets `keel init`, which seeds every rule at `candidate`
using each rule kind's CONSTRUCTOR DEFAULTS. Any parameter an operator tuned by hand is silently
replaced by the default: a DCA rule deliberately set to `budget_usd: 25` comes back as the
built-in `50`, at `candidate`, on a box that otherwise looks correctly provisioned. Nothing
errors. (That is a worked example rather than a description of today's deployment -- the live DCA
rule is now `50` on purpose, matching the constructor default and `config.dca.budget_usd`, which
is the value the live executor actually spends.) This module makes that state an artifact you can
diff in a PR instead of a fact that lives only on one laptop.

**`export`** writes the manifest. It is the source of truth's snapshot, not the source of truth:
re-run it and commit the diff whenever the live rule set changes deliberately.

**`apply`** rebuilds a database from the manifest. Two safety properties, both deliberate:

- It **never rewrites an existing rule's params.** Matching is by `(kind, product_id)`; a rule
  that exists with different params is reported as DRIFT and the run fails. Silently rewriting
  params from a JSON file would let an edited manifest change a LIVE rule's position size, which
  is exactly the kind of un-reviewed money change the promotion ladder exists to prevent.
  Reconcile drift deliberately, by hand.
- It **refuses to create `live` rules without `--allow-live`.** Seeding straight to `live` bypasses
  the promotion gate (same bypass as `keel rules seed --status live` and `rules promote --force`),
  so it takes an explicit flag and prints a loud warning, mirroring how those commands behave.

Dry-run is the default. Nothing is written without `--apply`.

Release tooling: deliberately NOT shipped in the wheel.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from keel.data.db import connect
from keel.data.repository import Repository

#: Statuses that can trade real money, and so require `--allow-live` to create from a manifest.
_ARMED_STATUSES = frozenset({"live"})


def _key(kind: str, params: dict[str, Any]) -> tuple[str, str]:
    """Identity of a rule for manifest purposes: its kind and product.

    Matches `keel rules seed`'s own idempotency key, so `apply` and `seed` agree on what "already
    exists" means rather than each having a private notion of duplicate.
    """
    return (kind, str(params.get("product_id", "")))


def export(db_path: str, out_path: Path) -> int:
    """Write every rule in `db_path` to `out_path` as JSON. Returns the number exported."""
    repo = Repository(connect(db_path))
    rules = [
        {"kind": row["kind"], "status": row["status"], "params": row["params"]}
        for row in repo.get_rules()
    ]
    manifest = {
        "_comment": (
            "Generated by scripts/rule_manifest.py -- the deployment's strategy library. "
            "Regenerate with `python scripts/rule_manifest.py export --db <db>` and commit the "
            "diff whenever the live rule set changes."
        ),
        "rules": rules,
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(manifest, indent=2) + "\n")
    return len(rules)


def apply(
    db_path: str,
    manifest_path: Path,
    *,
    write: bool = False,
    allow_live: bool = False,
) -> int:
    """Reconcile `db_path`'s rules against `manifest_path`.

    Returns a process exit code: 0 when the database matches (or was made to match) the manifest,
    1 when drift or a refused `live` insert means it does not.
    """
    manifest = json.loads(manifest_path.read_text())
    wanted = manifest["rules"] if isinstance(manifest, dict) else manifest

    repo = Repository(connect(db_path))
    existing = {_key(row["kind"], row["params"]): row for row in repo.get_rules()}

    to_insert: list[dict[str, Any]] = []
    drift: list[str] = []
    refused: list[str] = []

    for entry in wanted:
        kind, status, params = entry["kind"], entry["status"], entry["params"]
        key = _key(kind, params)
        current = existing.get(key)

        if current is None:
            if status in _ARMED_STATUSES and not allow_live:
                refused.append(f"{kind}:{key[1]} wants status={status}")
            else:
                to_insert.append(entry)
            continue

        if current["params"] != params:
            differing = sorted(
                k
                for k in set(current["params"]) | set(params)
                if current["params"].get(k) != params.get(k)
            )
            drift.append(
                f"{kind}:{key[1]} rule id={current['id']} params differ on {differing} "
                f"(db={ {k: current['params'].get(k) for k in differing} }, "
                f"manifest={ {k: params.get(k) for k in differing} })"
            )
        elif current["status"] != status:
            drift.append(
                f"{kind}:{key[1]} rule id={current['id']} status db={current['status']!r} "
                f"manifest={status!r} -- advance it with `keel rules promote`, not this script"
            )

    for entry in to_insert:
        key = _key(entry["kind"], entry["params"])
        verb = "would insert" if not write else "inserted"
        print(f"{verb}: {entry['kind']}:{key[1]} status={entry['status']}")
        if write:
            if entry["status"] in _ARMED_STATUSES:
                print(
                    f"  WARNING: created at status={entry['status']}, BYPASSING the promotion "
                    f"gate. This rule can place real orders as soon as the rails pass.",
                    file=sys.stderr,
                )
            repo.insert_rule(entry["kind"], entry["params"], status=entry["status"])

    for line in refused:
        print(f"REFUSED: {line} -- pass --allow-live to create armed rules", file=sys.stderr)
    for line in drift:
        print(f"DRIFT: {line}", file=sys.stderr)

    if not to_insert and not drift and not refused:
        print(f"in sync: {len(wanted)} rule(s) match {manifest_path}")
    elif not write and to_insert:
        print("\ndry run -- nothing written. Re-run with --apply to write.")

    return 1 if (drift or refused) else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_export = sub.add_parser("export", help="write the DB's rules to a JSON manifest")
    p_export.add_argument("--db", required=True, help="database to read")
    p_export.add_argument(
        "--out", type=Path, default=Path("deploy/live-rules.json"), help="manifest path to write"
    )

    p_apply = sub.add_parser("apply", help="rebuild a DB's rules from a JSON manifest")
    p_apply.add_argument("--db", required=True, help="database to write")
    p_apply.add_argument(
        "--manifest", type=Path, default=Path("deploy/live-rules.json"), help="manifest to read"
    )
    p_apply.add_argument(
        "--apply", action="store_true", dest="write", help="actually write (default: dry run)"
    )
    p_apply.add_argument(
        "--allow-live",
        action="store_true",
        help="permit creating rules at status=live, bypassing the promotion gate",
    )

    args = parser.parse_args(argv)

    if args.command == "export":
        count = export(args.db, args.out)
        print(f"exported {count} rule(s) to {args.out}")
        return 0
    return apply(args.db, args.manifest, write=args.write, allow_live=args.allow_live)


if __name__ == "__main__":
    raise SystemExit(main())
